name: Build

on:
  push:
    branches:
      - master

jobs:
  compile:
    strategy:
      fail-fast: false
      matrix:
        system: [ ubuntu-latest, windows-latest ]

    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build
        run: pyinstaller -F run.py

      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: run-${{matrix.system}}
          path: dist

  release:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - name: Download
        uses: actions/download-artifact@v2

      - name: Rename
        run: |
          mv run-ubuntu-latest run
          mv run-windows-latest run.exe

      - name: LS
        run: |
          ls
